onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bun
  - core-js
  - lmdb
  - msgpackr-extract
overrides:
  crosscode-typedef-inserter: link:../../../../.local/share/pnpm/global/5/node_modules/crosscode-typedef-inserter
